spring.application.name=VideoGameTriviaAPI

# Database connection settings
spring.datasource.url=jdbc:mysql://vehicle-database-do-user-17677292-0.d.db.ondigitalocean.com:25060/triviadb
spring.datasource.username=doadmin
spring.datasource.password=AVNS_Goc3od_KN2c4T5gMk2G
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# SSL settings
spring.datasource.hikari.data-source-properties.useSSL=true
spring.datasource.hikari.data-source-properties.requireSSL=true